const menu = [
    {
        id: 1,
        title: 'Filet Mignon',
        category: 'Main Courses',
        price: 50,
        img: './asset/images/filetmignon.png',
        desc: "Tender USDA prime filet mignon cooked to perfection and served with a rich red wine reduction, offering a luxurious dining experience with each bite.",
    },
    {
        id: 2,
        title: 'Lobster Thermidor',
        category: 'Main Courses',
        price: 60,
        img: './asset/images/lobsterthermidor.png',
        desc: "Indulge in the rich flavors of our Lobster Thermidor, featuring succulent lobster meat nestled in a creamy and decadent sauce, topped with a golden breadcrumb crust. ",
    },
    {
        id: 3,
        title: 'Seared Ahi Tuna',
        category: 'Main Courses',
        price: 45,
        img: './asset/images/searedahituna.png',
        desc: "Savor the exquisite taste of our Seared Ahi Tuna, where premium-grade tuna is delicately seared to perfection, resulting in a tender and melt-in-your-mouth experience. ",
    },
    {
        id: 4,
        title: 'Wild Mushroom Risotto',
        category: 'Main Courses',
        price: 35,
        img: './asset/images/wildmushroomrisotto.png',
        desc: "Indulge in the comforting richness of our Wild Mushroom Risotto, a culinary masterpiece that combines creamy Arborio rice with a medley of earthy wild mushrooms. ",
    },
    {
        id: 5,
        title: 'Gourmet Wagyu Burger',
        category: 'Main Courses',
        price: 30,
        img: './asset/images/gourmetwagyuburger.png',
        desc: "Savor the ultimate indulgence with our Gourmet Wagyu Burger, crafted from the finest Wagyu beef known for its unparalleled marbling and succulent flavor. ",
    },
    {
        id: 6,
        title: 'Truffle Fries',
        category: 'Side Dishes',
        price: 12,
        img: './asset/images/trufflefries.png',
        desc: "Experience a luxurious twist on a classic favorite with our Truffle Fries. Crispy hand-cut fries are elevated with a drizzle of fragrant truffle oil, imparting a rich and earthy flavor that perfectly complements the golden crispiness of each fry.",
    },
    {
        id: 7,
        title: "Grilled Asparagus",
        category: 'Side Dishes',
        price: 10,
        img: './asset/images/grilledasparagus.png',
        desc: "Savor the simplicity and elegance of our Grilled Asparagus. Tender spears of asparagus are delicately grilled to perfection, enhancing their natural sweetness and imparting a subtle smoky flavor.",
    },
    {
        id: 8,
        title: "Creamed Spinach",
        category: 'Side Dishes',
        price: 10,
        img: './asset/images/creamedspinach.png',
        desc: 'Indulge in the velvety richness of our Creamed Spinach. Fresh spinach leaves are gently sautéed and then enveloped in a luscious cream sauce infused with aromatic garlic, nutmeg, and a hint of Parmesan cheese.',
    },
    {
        id: 9,
        title: "Roasted Brussels Sprouts",
        category: 'Side Dishes',
        price: 12,
        img: './asset/images/roastedbrusselssprouts.png',
        desc: 'Experience the irresistible appeal of our Roasted Brussels Sprouts. Each tender sprout is lovingly roasted to perfection, creating a delightful caramelization that enhances its natural sweetness.',
    },
    {
        id: 10,
        title: "Garlic Mashed Potatoes",
        category: 'Side Dishes',
        price: 12,
        img: './asset/images/garlicmashedpotatoes.png',
        desc: 'Indulge in the creamy richness of our Garlic Mashed Potatoes, a classic comfort dish elevated to gourmet perfection. Made with premium potatoes, each velvety spoonful is infused with the unmistakable aroma and flavor of roasted garlic, adding a depth of savory goodness that tantalizes the taste buds.',
    },
    {
        id: 11,
        title: "Chardonnay Reserve",
        category: 'Wines',
        price: 45,
        img: './asset/images/chardonnayreserve.png',
        desc: "Indulge in our Chardonnay Reserve, a rich white wine with hints of tropical fruits and vanilla, balanced by a touch of oak. Perfect for pairing with seafood or creamy pasta dishes.",
    },
    {
        id: 12,
        title: "Pinot Grigio",
        category: 'Wines',
        price: 40,
        img: './asset/images/pinotgrigio.png',
        desc: "Savor our Pinot Grigio, a crisp and refreshing white wine featuring citrus notes and a clean, bright finish. Ideal for accompanying light salads or seafood dishes.",
    },
    {
        id: 13,
        title: "Merlot Classic",
        category: 'Wines',
        price: 50,
        img: './asset/images/merlotclassic.png',
        desc: "Indulge in our Merlot Classic, a smooth and velvety red wine with rich berry flavors and a hint of spice. Perfect for pairing with hearty meat dishes or savory pasta.",
    },
    {
        id: 14,
        title: "Craft Lager",
        category: 'Wines',
        price: 45.99,
        img: './asset/images/craftlager.png',
        desc: "Savor the crisp and refreshing taste of our Craft Lager, brewed with the finest ingredients for a clean, balanced flavor profile. Enjoy its smooth finish with notes of malt and hops.",
    },
    {
        id: 15,
        title: "India Pale Ale (IPA)",
        category: 'Wines',
        price: 38,
        img: '/asset/images/indiapaleale.png',
        desc: "Experience the bold and aromatic India Pale Ale (IPA), crafted with a perfect balance of hops and malt. Delight in its citrusy and floral notes, complemented by a hint of bitterness for a refreshing and flavorful brew.",
    },
    {
        id: 16,
        title: "Margarita",
        category: 'Cocktails',
        price: 12,
        img: './asset/images/margarita.png',
        desc: "Indulge in the classic Margarita, a tantalizing blend of tequila, lime, and a touch of salt. Savor the zesty citrus flavors and the subtle kick of tequila, perfectly balanced for a refreshing and invigorating cocktail.",
    },
    {
        id: 17,
        title: "Old Fashioned",
        category: 'Cocktails',
        price: 14,
        img: './asset/images/oldfashioned.png',
        desc: "Experience the timeless allure of the Old Fashioned, a sophisticated concoction of bourbon, sugar, and bitters. Revel in the rich depth of bourbon, subtly sweetened with sugar and elevated with aromatic bitters for a truly refined drinking experience.",
    },
    {
        id: 18,
        title: "Martini",
        category: 'Cocktails',
        price: 13,
        img: './asset/images/martini.png',
        desc: "Elevate your spirits with the iconic Martini, a classic blend of gin and vermouth garnished with a briny olive. Savor the smooth, botanical notes of gin perfectly balanced with the herbal complexity of vermouth, culminating in a sophisticated and timeless cocktail.",
    },
    {
        id: 19,
        title: "Mojito",
        category: 'Cocktails',
        price: 11,
        img: './asset/images/mojito.png',
        desc: "Transport yourself to the tropics with the refreshing Mojito, a tantalizing fusion of rum, mint, lime, and soda. Experience the vibrant flavors of fresh mint and zesty lime melded with the subtle sweetness of rum, creating a crisp and invigorating cocktail that's perfect for any occasion.",
    },
    {
        id: 20,
        title: "Negroni",
        category: 'Cocktails',
        price: 15,
        img: './asset/images/negroni.png',
        desc: "Experience the bold and timeless Negroni, a sophisticated blend of gin, Campari, and vermouth. With its vibrant ruby hue and complex flavor profile, this classic cocktail offers a harmonious balance of herbal bitterness, citrusy notes, and botanical undertones.",
    },
    {
        id: 21,
        title: "Truffle Arancini",
        category: "Appetizers",
        price: 12,
        img: "./asset/images/trufflearancini.png",
        desc: "Indulge in our exquisite Truffle Arancini, crispy risotto balls filled with creamy mozzarella and aromatic black truffle. Each bite is a symphony of flavors, combining the earthy richness of truffle with the gooey decadence of melted cheese."
    },
    
    {
        id: 22,
        title: "Seared Scallops",
        category: "Appetizers",
        price: 14,
        img: "./asset/images/searedscallops.png",
        desc: "Delight your palate with our Seared Scallops, perfectly caramelized and served atop a bed of velvety cauliflower puree. Each succulent scallop is bursting with sweet and savory flavors, complemented by the subtle nuttiness of the puree."
    },
    
    {
        id: 23,
        title: "Caprese Salad",
        category: "Appetizers",
        price: 10,
        img: "./asset/images/capresesalad.png",
        desc: "Savor the freshness of summer with our Caprese Salad, featuring ripe heirloom tomatoes, creamy buffalo mozzarella, and fragrant basil leaves drizzled with balsamic glaze. This vibrant dish is a celebration of simple ingredients and bold flavors."
    },
    
    {
        id: 24,
        title: "Tomato Basil Soup",
        category: 'Appetizers',
        price: 10,
        img: './asset/images/tomatobasilsoup.png',
        desc: "Indulge in the comforting flavors of our Tomato Basil Soup, made from ripe tomatoes, fragrant basil, and a hint of cream for richness.",
        },
    
    {
        id: 25,
        title: "Artisan Charcuterie Board",
        category: "Appetizers",
        price: 18,
        img: "./asset/images/cartisancharcuterieboard.png",
        desc: "Embark on a culinary journey with our Artisan Charcuterie Board, an exquisite selection of cured meats, artisanal cheeses, house-made pickles, and crusty bread. Perfect for sharing, this platter offers a tantalizing array of flavors and textures."
    },
    {
        id: 26,
        title: "Prosperity Abalone Salad",
        category: 'Seasonal Items',
        price: 39,
        img: './asset/images/abalonesalad.png',
        desc: "Celebrate prosperity and abundance with our exquisite Abalone Salad, featuring tender abalone slices, crisp mixed greens, and a tangy plum dressing, symbolizing good fortune and success in the coming year.",
    },
    {
        id: 27,
        title: "Golden Dumplings with Truffle Sauce",
        category: 'Seasonal Items',
        price: 29,
        img: './asset/images/goldendumplings.png',
        desc: "Indulge in luxury with our Golden Dumplings, delicately crafted from premium ingredients and adorned with edible gold leaf, served with a decadent truffle sauce, symbolizing wealth and prosperity for the new year.",
    },
    {
        id: 28,
        title: "Braised Pork Belly with Glutinous Rice",
        category: 'Seasonal Items',
        price: 49,
        img: './asset/images/braisedpork.png',
        desc: "Experience the rich flavors of tradition with our Braised Pork Belly, slow-cooked to perfection and served atop a bed of fragrant glutinous rice, symbolizing reunion and harmony with loved ones during the festive season.",
    },
    {
        id: 29,
        title: "Lucky Fish with Ginger and Scallions",
        category: 'Seasonal Items',
        price: 59,
        img: './asset/images/luckyfish.png',
        desc: "Embrace good fortune and prosperity with our Lucky Fish, delicately steamed and dressed with aromatic ginger and scallions, symbolizing abundance and surplus for the new year ahead.",
    },
    {
        id: 30,
        title: "Golden Pineapple Tarts",
        category: 'Seasonal Items',
        price: 19,
        img: './asset/images/pineappletarts.png',
        desc: "Sweeten your celebrations with our Golden Pineapple Tarts, handmade with love and filled with luscious pineapple jam, symbolizing wealth, luck, and sweet blessings for the new year.",
    },    
      ];
      
      export default menu;
      